### ISSUE TITLE
well.save error

### ISSUE THREAD

**Issue by nrepina** [fmi-faim/faim-hcs#1]
When adding measurement and saving to well-level measurements, gives error: 
TypeError: Cannot interpret '<attribute 'dtype' of 'numpy.generic' objects>' as a data type

It does save, but always throws this error. Emailed you my jupyter notebook so you can take a closer look at the tracebacks. 

I think this only happens when the exp is first loaded from disk (from the summary file), because I do not get this error in my feature extraction script where I generate a new exp.

**Comment by tibuch** [comment]
I added well save and load test and can't reproduce this issue anymore.
