### ISSUE TITLE
Legacy STK Support

### ISSUE THREAD

**Issue by jeskowagner** [fmi-faim/faim-hcs#18]
Hi!

Thanks for making this package. I'd love to turn my HTS ImageXpress data into `ome-zarr` and was hoping `faim-hcs` could help with that. While running through the [tutorial](https://github.com/fmi-faim/faim-hcs/blob/main/examples/Create%20ome-zarr%20from%20Single-Plane%20Multi-Field%20Acquisition.ipynb) I unfortunately encountered issues at the `get_well_image_CYX` step. Specifically, it appears that my images are not a `metaseries` as required by [`load_metaseries_tiff`](https://github.com/fmi-faim/faim-hcs/blob/main/src/faim_hcs/io/MetaSeriesTiff.py#L40).

I checked and my data format instead appears to be [STK](https://support.moleculardevices.com/s/article/MetaMorph-Software-TIFF-and-STK-file-formats) (although the files themselves still have the `.tif` suffix). Indeed, using `tifffile.TiffFile(<myfile>).stk_metadata` I can read my metadata just fine.

If I understand correctly, [Molecular Devices](https://support.moleculardevices.com/s/article/MDA-file-formats) seems to say that STK is now legacy, and that newer versions should be using the Meta Series format. But unfortunately I am not the creator of these images and would prefer not having to mess with the metadata just to transform the data to `ome-zarr`.

Are there any plans to allow extraction of metadata from formats other than metadata series?

Thanks! Best,

Jesko

**Comment by jeskowagner** [comment]
Hi @tibuch,

Thanks for your help! I just got started on a PR, but am unsure which keys of STK metadata would map to the right keys in the metaseries format. Below is the type of metadata I get from STKs.

<details>
<summary>STK metadata</summary>

```javascript
// Note that some information was omitted
// because the data is not yet public
{'PlaneDescriptions': {
  'Plate Name: omitted',
  'Folder Name: omitted',
  'Barcode:omitted',
  'omitted',
  'Exposure: 200 ms',
  'Binning: 1 x 1',
  'Region: 2160 x 2160, offset at (200, 0)',
  'Acquired from PCO.SDK Camera',
  'Subtract: Off',
  'Shading: Off',
  'Digitizer: 95.33 MHz',
  'Gain: Gain 1 (0.45 e/cnt)',
  'Spot Noise Reducer Enabled: Yes',
  'Frames to Average: 1',
  'Trigger Mode: Normal (TIMED)',
  'Temperature: 20.3',
  'Deconvolution NA: 0.45',
  'Deconvolution RI: 1',
  'Deconvolution Emissive Wavelength: 525',
  'Deconvolution X Image Spacing: 0.325',
  'Deconvolution Y Image Spacing: 0.325',
  'Deconvolution Spherical Aberration: 0',
  'Deconvolution Wiener Filter KValue: 0.141589'
  },
 'NumberPlanes': 1,
 'AutoScale': 1,
 'MinScale': 0,
 'MaxScale': 62577,
 'SpatialCalibration': 1,
 'XCalibration': 0.325,
 'YCalibration': 0.325,
 'CalibrationUnits': 'um',
 'Name': 'FITC',
 'ThreshState': 0,
 'ThreshStateRed': 255,
 'ThreshStateGreen': 128,
 'ThreshStateBlue': 64,
 'ThreshStateLo': 0,
 'ThreshStateHi': 65535,
 'Zoom': 33,
 'CreateTime': datetime.datetime(2019, 9, 22, 0, 8, 49, 406),
 'LastSavedTime': datetime.datetime(2019, 9, 22, 0, 8, 50, 160),
 '_grayFit': 4,
 '_grayPointCount': 0,
 'grayX': 4294967295.0,
 'grayY': 4294967295.0,
 'grayMin': 4294967295.0,
 'grayMax': 4294967295.0,
 'StandardLUT': 0,
 'wavelength': 525,
 'AutoScaleLoInfo': 0.0,
 'AutoScaleHiInfo': 0.0,
 'Gamma': None,
 'CameraBin': None,
 'NewLUT': 0,
 'PlaneProperty': 9349986,
 '_TagId67': 9350047}
```
</details>

I have not yet seen which metaseries keys contain which values. But just going by key names, I would presume the following mapping:

<details>
<summary>Metadata key mappings</summary>

```javascript
{
    "_IllumSetting_" : "???",
    "spatial-calibration-x": "XCalibration",
    "spatial-calibration-y": "YCalibration",
    "spatial-calibration-units": "CalibrationUnits",
    "stage-position-x": "???",
    "stage-position-y": "???",
    "z-position": "???",
    "_MagNA_": "Zoom",
    "_MagSetting_": "???",
    "Exposure Time",
    "Lumencor Cyan Intensity": "ThreshStateBlue",
    "Lumencor Green Intensity": "ThreshStateGreen",
    "Lumencor Red Intensity": "ThreshStateRed",
    "Lumencor Violet Intensity": "???",
    "Lumencor Yellow Intensity": "???",
    "ShadingCorrection": "Shading",
    "stage-label": "???",
    "SiteX": "???",
    "SiteY": "???",
    "wavelength": "wavelength",
    "Z Step": "???",  // optional
    "Z Projection Method": "???",  // optional
    "Z Projection Step Size": "???",  // optional
}
```
</details>

I am not sure about some of those mappings, and for some others I don't think there is any valid mapping (marked `???`). Would you be able to provide example values for the keys you request in [load_metaseries_tiff](https://github.com/fmi-faim/faim-hcs/blob/main/src/faim_hcs/io/MetaSeriesTiff.py#L7)? That would help me get the mapping right (or at least improve it).

Thanks! Best,

Jesko

**Comment by tibuch** [comment]
Cool!

These would be the fields from file `resources/Projection-Mix/2023-02-21/1334/Projection-Mix_E07_s1_w1E94C24BD-45E4-450A-9919-257C714278F7.tif`:
```
{'_IllumSetting_': 'FITC_05', # Channel name set by the user in the acquisition software.
 'spatial-calibration-x': 1.3668,
 'spatial-calibration-y': 1.3668,
 'spatial-calibration-units': 'um',
 'stage-position-x': 79813.4, # Used to montage/stitch the images. 
 'stage-position-y': 41385.4, # Used to montage/stitch the images
 'z-position': 9343.19, # Used to montage/stitch the images
 '_MagNA_': 0.75,
 '_MagSetting_': '20X Plan Apo Lambda',
 'Exposure Time': '15 ms',
 'Lumencor Cyan Intensity': 5.09804,
 'Lumencor Green Intensity': 0.0,
 'Lumencor Red Intensity': 0.0,
 'Lumencor Violet Intensity': 0.0, # If missing, I would just set them to zero. 
 'Lumencor Yellow Intensity': 0.0,
 'ShadingCorrection': 'Off',
 'stage-label': 'E07 : Site 1',
 'SiteX': 1.0,
 'SiteY': 1.0,
 'wavelength': 536.0,
 'Z Projection Method': 'Maximum', # Optional, used in case only projected data is stored.
 'Z Projection Step Size': 5.0,
 'PixelType': 'uint16'}
```

`stage-position-x`, `stage-postion-y` and `z-position` are used to montage the images together. If they are not part of the metadata we might have to fake them and get them via user-input?

**Comment by jeskowagner** [comment]
Thanks for your swift response!

`stage-position-x`, `stage-postion-y` and `z-position` will be tricky indeed. Perhaps I can compute them from the row and columns that you extract from the file names, then multiply the row/column index by the number of pixels in the image rows/columns. I don't have Z-stacks at the moment, so would require another mind to think up solutions for that bit.

For the `stage-label` I could use a similar approach, by just merging well and site names.

The `PixelType` I should be able to extract using `numpy`.

Could you please still elaborate on what `_MagNA_`, `SiteX`, and `SiteY` are?

**Comment by jeskowagner** [comment]
Sadly I have multiple sites per well, so am unsure why that data is missing. Without information by the user I don't see how I could impute the arrangements of sites in a well. Perhaps I will have to create a separate argument for that. Regarding `_MagNA_`, it appears that this is not at all captured in my STKs. Tricky, but perhaps best to just put `1` or a similar value for now, though that's not a great solution...

**Comment by imagejan** [comment]
@jeskowagner what about this:
```
'Region: 2160 x 2160, offset at (200, 0)',
```

Does the offset tell anything about the position of the field within the well?

**Comment by jeskowagner** [comment]
@imagejan Nice guess, I hadn't spotted that! Sadly, it appears that this value is constant across wells and fields within a well in my dataset.

**Comment by jeskowagner** [comment]
I have started work on this [here](https://github.com/jeskowagner/faim-hcs/tree/legacy_stk). However, I am still undecided on how to best obtain stage positions and spacings. Would appreciate help of anyone who works with STKs.

**Comment by jeskowagner** [comment]
I am not sure I understand why the `stage-position` is divided by the `spatial-calibration` (here)[https://github.com/fmi-faim/faim-hcs/blob/main/src/faim_hcs/MetaSeriesUtils.py#L159]. Could someone shed some light on that please? Still looking to assemble my STKs somehow.

**Comment by imagejan** [comment]
> I am still undecided on how to best obtain stage positions.

If the position isn't present in the file metadata, then you have no chance. Do you maybe have secondary files defining how the tile layout looks, from where you could deduce the position of each tile? Or you could provide a mapping of field index to position at runtime... do you actually know how your fields are laid out per well, and if so, how?

> Would appreciate help of anyone who works with STKs.
There are different flavors of `stk`s (i.e. the MetaMorph 1.0 format). For example, we have a bunch of VisiView systems that create `nd`/`stk` datasets, but without the context of multi-well plates. Those datasets do have some positional information stored in the tiff tags.

> I am not sure I understand why the `stage-position `is divided by the `spatial-calibration`
The stage position metadata usually are in micrometers. The `_pixel_pos` function converts between calibrated (micrometer) positions and pixel units. We need that in order to assemble the fields into a regular grid.

**Comment by imagejan** [comment]
Great to know you're making progress, @jeskowagner!

> I should be able to set my spatial-calibration to 1 in that case,

Ideally, the spatial calibration values (as well as your stage positions) should reflect real world measurements, so that you can measure the size of objects etc. later.

**Comment by jeskowagner** [comment]
Closing this for now, because I do not have sufficient STK data to play with and see whether the planned implementation would work. There's no point in implementing a feature if it only works for this single dataset I have. If anyone has more diverse STK data let me know!
