### ISSUE TITLE
How to get path to where raw organoid images are saved?

### ISSUE THREAD

**Issue by nrepina** [fmi-faim/faim-hcs#2]
I think the function that should do this is get_organoid_dir() in OrganoidRecord however get error:

'WellRecord' object has no attribute 'get_well_dir'

Indeed there is no function get_well_dir in WellRecord.

When calling organoid_dir() I get path to the faim-hcs data structure, not to the raw data.

**Comment by tibuch** [comment]
You can get the image data directly from the `OrganoidRecord` with `org.get_raw_data(name)` where `name` corresponds to the name given with `org.add_raw_data(name, path, spacing)`.

Alternatively, one can ask the `Experiment` to get the organoid raw-files with `exp.get_organoid_raw_files(name)`.

The current implementation has no `get_organoid_dir()` function.
