### ISSUE TITLE
`get_wavelength_power` function fails with KeyError for MDs with other wavelength metadata

### ISSUE THREAD

**Issue by jluethi** [fmi-faim/faim-hcs#35]
The current setup of `get_wavelength_power` in MetaSeriesUtils.py only works for MD setups that contain the following wavelength power settings in their metadata:
["Lumencor Cyan Intensity", "Lumencor Green Intensity", "Lumencor Red Intensity", "Lumencor Violet Intensity", "Lumencor Yellow Intensity"]

If one or multiple of them are missing, it raises a `KeyError`. Also, if other intensity values are part of the metadata, they are ignored.
At the ZMB, they have other lamps, thus other metadata. I'd suggest we make this metadata readout more general (PR coming up), such that it would work with other MD configurations and the configurations don't need to be part of the faim-hcs source code.

**Comment by tibuch** [comment]
Removed this function in #59. Now only the `wavelength` is extracted from the metadata.
