### ISSUE TITLE
Compress tiff test data

### ISSUE THREAD

**Issue by imagejan** [fmi-faim/faim-hcs#6]
Let's compress the test data `.tif` files using `tifffile` while keeping the original MolecularDevices metadata, and replacing all pixel values by `0`.

We can possibly use [this code snippet mentioned on the forum](https://forum.image.sc/t/resaving-ome-tiff-as-compressed-while-keeping-metadata-intact/75627/2?u=imagejan
) to re-write all the tiff tags.

**Comment by tibuch** [comment]
Thanks! Merged.
