### ISSUE TITLE
Improve README.md

### ISSUE THREAD

**Issue by tibuch** [fmi-faim/faim-hcs#9]

**Comment by adityakode** [comment]
Can I work on this?

**Comment by adityakode** [comment]
Hi @tibuch!
I have made a [Readme.md](https://github.com/adityakode/faim-hcs/blob/fixReadme.md/README.md) file.
Can you please review it and suggest me the changes and other requirements in it?

**Comment by tibuch** [comment]
Nice try, but I think this needs a bit more substance. I will add an improved version later and you are welcome to compare it to your suggested README once this issue is resolved.
